- name: deploy one petclinic to one server
  hosts: service
  become: yes

  tasks:
  - name: Check current directory and list target directory
      command: ls -la ./target
      register: output

    - name: Debug output
      debug:
        msg: "{{ output.stdout }}"

    - name: Find the jar file in the target directory
      find:
        paths: "./target"
        patterns: "*.jar"
        use_regex: false
      register: jar_files
    - name: Fail if no jar file is found
      fail:
        msg: "No jar file found in target directory."
      when: jar_files.matched == 0
    
    - name: copy the jar file to target host
      copy:
        src: "{{ jar_files.files[0].path }}"
        dest: ./petclinic.jar
      become: yes
    - name: install openjdk17
      become: yes
      apt:
        name: openjdk-17-jre
        state: latest
        update_cache: yes
    - name: run the jar file
      shell: nohup java -jar petclinic.jar &
      args:
        executable: /bin/bash