- name: deploy one petclinic to one server
  hosts: service
  become: yes

  tasks:
    - name: Fail if no jar file is found
      fail:
        msg: "No jar file found in target directory."
      when: jar_files.matched == 0
    
    - name: copy the jar file to target host
      copy:
        src: "{{JAR_FILE}}"
        dest: ./petclinic.jar
      become: yes
    - name: install openjdk17
      become: yes
      apt:
        name: openjdk-17-jre
        state: latest
        update_cache: yes
    - name: run the jar file
      shell: nohup java -jar petclinic.jar &
      args:
        executable: /bin/bash